services:
  - type: web
    name: fertismart-backend
    env: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_DEBUG
        value: "False"
      - key: PORT
        value: 10000

  - type: static
    name: fertismart-frontend
    env: static
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://fertismart-backend.onrender.com
